### ISSUE TITLE
Github release and docker tags

### ISSUE THREAD

**Issue by k0da** [ns1/cert-manager-webhook-ns1#10]
please consider having github releases and reflect them into docker tags. This will help users to test and rollout exact images versions into their environment.

**Comment by mburtless** [comment]
Thanks for the feedback, definitely something we'd like to tackle as bandwidth allows.

**Comment by dennisme** [comment]
+1 to this.

**Comment by Zach-Johnson** [comment]
The latest v0.4.1 release has been tagged, as well as the docker image for it. We'll continue this going forward. Thanks!
