### ISSUE TITLE
v0.4.3 released container image is not working

### ISSUE THREAD

**Issue by Restless-ET** [ns1/cert-manager-webhook-ns1#34]
Getting the following error:

> exec /usr/local/bin/webhook: exec format error

Maybe the architecture (or something else) changed on this last build. 🤔

**Comment by jfarrell-NS1** [comment]
@Restless-ET Can you please try re-pulling the v0.4.3 image, I've made an update that should fix the issue

**Comment by Restless-ET** [comment]
New v0.4.3 tagged image seems to be working fine. 👌 

Thank you for your prompt answer+fix and sorry for the late reply.
