### ISSUE TITLE
Image no longer exists in dockerhub

### ISSUE THREAD

**Issue by tylerauerbeck** [ns1/cert-manager-webhook-ns1#48]
It appears this image is no longer is present on Dockerhub (and in fact `ns1inc` has disappeared completely)

```Error response from daemon: pull access denied for ns1inc/cert-manager-webhook-ns1, repository does not exist or may require 'docker login'```

**Comment by gchaviaras-NS1** [comment]
Fixed at https://github.com/ns1/cert-manager-webhook-ns1/releases/tag/v0.4.4
Thanks for the feedback !
