### ISSUE TITLE
Server is currently unable to handle the request

### ISSUE THREAD

**Issue by alexgreco86** [ns1/cert-manager-webhook-ns1#9]
I've gone through the installation steps but I'm still getting a `the server is currently unable to handle the request (post ns1.acme.nsone.net)` error.  I'm wondering perhaps if its an issue with my K8s version or perhaps there are more helpful ways I can debug this as the only output I have is from the cert-manager logs, as the other pods don't have any error messages.

Thus far:
- The NS1 API key being used has sufficient privileges to access and modify resources in NS1. 
- I'm able to switch over to use ACME via HTTP or a a custom Vault issuer I made and the certs generate just fine.
- The `extension-apiserver-authentication-reader` note was addressed considering our k8s version.
- I've been able to use the Certificate resource AND Ingress Shim via those alternate issuers - however I get the same errors on both using this webhook.
- We are currently running on Kubernetes 1.14.10.  I know this was tested on >1.16.2 so I'm wondering if the issue is here.
- The ClusterRole, ClusterRoleBinding and ClusterIssuer resources were generated exactly like in the example, albeit using the names I configured.

**Debugging:**

The Issuer seems to be created successfully:
```
  Conditions:
    Last Transition Time:  2020-03-12T20:47:18Z
    Message:               The ACME account was registered with the ACME server
    Reason:                ACMEAccountRegistered
    Status:                True
    Type:                  Ready
Events:                    <none>
```
Cert-Manager logs only indicate an error:
```
I0313 20:53:35.678912       1 dns.go:92] cert-manager/controller/challenges/Present "msg"="presenting DNS01 challenge for domain" "dnsName"="MYDOMAIN.MYCOMPANY.COM" "domain"="MYDOMAIN.MYCOMPANY.COM" "resource_kind"="Challenge" "resource_name"="cert-manager-acme-ns1-crt-774713317-2913930695-3538686115" "resource_namespace"="cert-manager" "type"="dns-01"
E0313 20:53:35.681107       1 controller.go:131] cert-manager/controller/challenges "msg"="re-queuing item  due to error processing" "error"="the server is currently unable to handle the request (post ns1.acme.nsone.net)" "key"="cert-manager/cert-manager-acme-ns1-crt-774713317-2913930695-3538686115"
```
Description of certificaterequest:
```
Name:         cert-manager-acme-ns1-crt-774713317
Namespace:    cert-manager
Labels:       <none>
Annotations:  cert-manager.io/certificate-name: cert-manager-acme-ns1-crt
              cert-manager.io/private-key-secret-name: cert-manager-acme-ns1-crt
API Version:  cert-manager.io/v1alpha2
Kind:         CertificateRequest
Metadata:
  Creation Timestamp:  2020-03-13T20:48:29Z
  Generation:          1
  Owner References:
    API Version:           cert-manager.io/v1alpha2
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Certificate
    Name:                  cert-manager-acme-ns1-crt
    UID:                   fe5f5ed8-656b-11ea-83c4-42010a9af824
  Resource Version:        57047288
  Self Link:               /apis/cert-manager.io/v1alpha2/namespaces/cert-manager/certificaterequests/cert-manager-acme-ns1-crt-774713317
  UID:                     fe63a764-656b-11ea-83c4-42010a9af824
Spec:
  Csr:  <OBFUSCATED>
  Issuer Ref:
    Group:  cert-manager.io
    Kind:   ClusterIssuer
    Name:   acme-ns1-issuer
Status:
  Conditions:
    Last Transition Time:  2020-03-13T20:48:29Z
    Message:               Waiting on certificate issuance from order cert-manager/cert-manager-acme-ns1-crt-774713317-2913930695: "pending"
    Reason:                Pending
    Status:                False
    Type:                  Ready
Events:
  Type    Reason        Age   From          Message
  ----    ------        ----  ----          -------
  Normal  OrderCreated  20m   cert-manager  Created Order resource cert-manager/cert-manager-acme-ns1-crt-774713317-2913930695
```

```
Helm Version: 2.11
Cert-Manager Version: v0.13.0
Kubernetes Master: 1.14.10-gke.17
```

Any insight into this would be much appreciated - I can provide more information as well if needed.

**Comment by rupa** [comment]
this certainly doesn't look right, looks like something is trying to POST to `ns1.acme.nsone.net` and that shouldn't be happening. The only mention of `acme.nsone.net` in the repo is in the `groupName`, which should not need to be changed or edited.

My suspicion is that your Issuer isn't set up quite right, if you can find where `ns1.acme.nsone.net` is coming from, that's likely a problem point.

**Comment by alexgreco86** [comment]
> My suspicion is that your Issuer isn't set up quite right, if you can find where `ns1.acme.nsone.net` is coming from, that's likely a problem point.
> 

I tested against the issuer we templated and the one provided in the instructions - I haven't edited the groupName as per the comments.  

So one thing I noticed is if I remove the solver name:
```
groupName: acme.nsone.net
#solverName: ns1
```
, it no longer appends the `ns1` to the URL, and I no longer get the error.  However the cert is never created, it kinda loops with a `CertificateRequest is not in a final state, waiting until CertificateRequest is complete` status.

```
I0316 17:37:50.421492       1 sync.go:385] cert-manager/controller/certificates "msg"="validating existing CSR data" "related_resource_kind"="CertificateRequest" "related_resource_name"="cert-manager-acme-ns1-crtv3-2813827056" "related_resource_namespace"="cert-manager" "resource_kind"="Certificate" "resource_name"="cert-manager-acme-ns1-crtv3" "resource_namespace"="cert-manager"
I0316 17:37:50.421887       1 sync.go:497] cert-manager/controller/certificates "msg"="CertificateRequest is not in a final state, waiting until CertificateRequest is complete" "related_resource_kind"="CertificateRequest" "related_resource_name"="cert-manager-acme-ns1-crtv3-2813827056" "related_resource_namespace"="cert-manager" "resource_kind"="Certificate" "resource_name"="cert-manager-acme-ns1-crtv3" "resource_namespace"="cert-manager" "state"="Pending"
I0316 17:37:50.422146       1 controller.go:135] cert-manager/controller/certificates "msg"="finished processing work item" "key"="cert-manager/cert-manager-acme-ns1-crtv3"
I0316 17:37:56.369729       1 controller.go:129] cert-manager/controller/ingress-shim "msg"="syncing item" "key"="cert-manager/cert-manager-acme-ingress"
I0316 17:37:56.369830       1 sync.go:163] cert-manager/controller/ingress-shim "msg"="certificate already exists for ingress resource, ensuring it is up to date" "related_resource_kind"="Certificate" "related_resource_name"="cert-manager-acme-ns1-crtv3" "related_resource_namespace"="cert-manager" "resource_kind"="Ingress" "resource_name"="cert-manager-acme-ingress" "resource_namespace"="cert-manager"
I0316 17:37:56.369856       1 sync.go:176] cert-manager/controller/ingress-shim "msg"="certificate resource is already up to date for ingress" "related_resource_kind"="Certificate" "related_resource_name"="cert-manager-acme-ns1-crtv3" "related_resource_namespace"="cert-manager" "resource_kind"="Ingress" "resource_name"="cert-manager-acme-ingress" "resource_namespace"="cert-manager"
I0316 17:37:56.369883       1 controller.go:135] cert-manager/controller/ingress-shim "msg"="finished processing work item" "key"="cert-manager/cert-manager-acme-ingress"

```

**Comment by rupa** [comment]
`solverName` is supposed to be there and be set to `ns1`.

In case it's not clear, the `endpoint` and `ignoreSSL` arguments in the `Issuer/ClusterIssuer` resources are currently required. They cannot be omitted even if you are using the default settings as shown in the README

**Comment by alexgreco86** [comment]
So this is the staging issuer I've been working with - anytime the solverName is populated, it prepends to the URL(I tried with ns1, test123):
```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: acme-ns1-issuer
spec:
  acme:
    email: myname@mycompanyname.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-ns1-issuer-staging-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.nsone.net
          solverName: ns1
          config:
            apiKeySecretRef:
              key: apiKey
              name: ns1-credentials
            # Replace this with your NS1 API endpoint if not using "managed"
            endpoint: "https://api.nsone.net/v1/"
            ignoreSSL: false
```

**Comment by rupa** [comment]
that does look correct to me.

Have you followed the `CertificateRequest` resource chain farther? i.e look at the `Order` that the   `CertificateRequest` is waiting on, and the `OrderRequest` and so on ... I've had good luck with a useful error message at the end of them when the logs aren't as helpful as I'd like

**Comment by alexgreco86** [comment]
We've discovered the issue and it was due to needing a firewall rule/ingress created for port :8443 from the gke cluster so the APIService can be discovered.  Thanks for your help!

**Comment by ipince** [comment]
> We've discovered the issue and it was due to needing a firewall rule/ingress created for port :8443 from the gke cluster so the APIService can be discovered. Thanks for your help!

Can you provide some more information please? I'm running into the exact same problem. Thanks!

**Comment by ipince** [comment]
In case someone from the future reads this, I solved this problem by going to the GCP console and creating a new Firewall Rule with the following settings:
* Network: the VPC network of my cluster
* Type: Ingress
* Action: Allow
* Targets: All instances in the network
* IP ranges: `0.0.0.0/0`
* Protocols and ports: `tcp:8443`

Hope that helps
